/**
 * clientCtrl
 * Generated by devups
 * on 2022/02/02
 */

function changeStatus(id, status, el) {
    if (!confirm("Confirmer le changement de status?"))
        return;

    model.addLoader($(el))
    Drequest.init(__env+"admin/api/user.changestatus?id=" + id+"&status="+status)
        /*.data({
            user:{
                can_sponsoring:status
            }
        })*/
        .get((response) => {
            console.log(response)
            model.init("user")
            ddatatable.replacerow(id, response.tablerow.row)
        })
}
