/**
            * push_subscriptionCtrl
            * Generated by devups
            * on 2022/10/18
            */


function testPush(id, el) {
    if (!confirm("Confirmer le test?"))
        return;

    model.addLoader($(el))

    Drequest.init(__env+"admin/api/push_subscription/testPushNotif?id=" + id)
        .get((response) => {
            console.log(response)
            model.removeLoader()
        })
}