/**
            * workersCtrl
            * Generated by devups
            * on 2025/05/12
            */



function testPush(id, el) {
    if (!confirm("Confirmer le test?"))
        return;

    model.addLoader($(el))

    Drequest.init(__env+"admin/api/workers/testPushNotif?id=" + id)
        .get((response) => {
            console.log(response)
            model.removeLoader()
        })
}